name: 'dbt_dental_practice'
version: '1.0.0'
config-version: 2

profile: 'mdc_analytics'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  dbt_dental_practice:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
