version: 2

models:
  - name: int_patient_profile
    description: "Consolidated patient demographic information and contact details"
    meta:
      owner: "Clinical Team"
      refresh: "daily"
      business_system: "Core Patient Data"
    columns:
      - name: patient_id
        description: "Unique identifier for a patient"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Patient's first name"
      - name: last_name
        description: "Patient's last name"
      - name: birthdate
        description: "Patient's date of birth"
      - name: phone
        description: "Patient's primary phone number"
      - name: email
        description: "Patient's email address"
      - name: family_id
        description: "Identifier for the patient's family grouping"
      - name: city
        description: "Patient's city of residence from zipcode lookup"
      - name: state
        description: "Patient's state of residence from zipcode lookup"
      - name: model_created_at
        description: "Timestamp when this model was created"
      - name: model_updated_at
        description: "Timestamp when this model was last updated"

  - name: int_appointment_details
    description: "Enhanced appointment information with type, provider, and status"
    meta:
      owner: "Scheduling Team"
      refresh: "daily"
      business_system: "System G: Scheduling & Referrals"
    columns:
      - name: appointment_id
        description: "Unique identifier for an appointment"
        tests:
          - unique
          - not_null
      - name: patient_id
        description: "Patient associated with the appointment"
        tests:
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: provider_id
        description: "Provider assigned to the appointment"
      - name: appointment_date
        description: "Date of the appointment"
        tests:
          - not_null
      - name: appointment_time
        description: "Time of the appointment"
      - name: appointment_status
        description: "Current status of the appointment (e.g., scheduled, confirmed)"
      - name: is_confirmed
        description: "Flag indicating if the appointment has been confirmed"
      - name: is_complete
        description: "Flag indicating if the appointment has been completed"
      - name: is_hygiene
        description: "Flag indicating if this is a hygiene appointment"
      - name: appointment_type_name
        description: "Name of the appointment type"
      - name: appointment_length
        description: "Duration of the appointment in minutes"
      - name: provider_name
        description: "Name of the provider"
      - name: provider_specialty
        description: "Provider's area of specialty"
      - name: appointment_status_desc
        description: "Human-readable description of the appointment status"

  - name: int_procedure_complete
    description: "Comprehensive procedure data including codes, fees, and notes"
    meta:
      owner: "Clinical Team"
      refresh: "daily"
      business_system: "System A: Fee Processing & Verification"
    columns:
      - name: procedure_id
        description: "Unique identifier for a procedure"
        tests:
          - unique
          - not_null
      - name: patient_id
        description: "Patient who received the procedure"
        tests:
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: provider_id
        description: "Provider who performed the procedure"
      - name: procedure_date
        description: "Date the procedure was performed"
      - name: procedure_status
        description: "Status of the procedure (C=Complete, EC=Existing Complete, TP=Treatment Plan, etc.)"
        tests:
          - accepted_values:
              values: ['C', 'EC', 'EO', 'R', 'TP', 'D']
      - name: procedure_status_desc
        description: "Human-readable description of the procedure status"
      - name: procedure_code
        description: "Code representing the procedure (typically ADA codes)"
      - name: procedure_description
        description: "Description of the procedure"
      - name: fee
        description: "Fee charged for the procedure"
        tests:
          - not_null
      - name: fee_schedule_id
        description: "Identifier for the fee schedule used"
      - name: fee_schedule_name
        description: "Name of the fee schedule applied"
      - name: procedure_note
        description: "Clinical notes related to the procedure"

  - name: int_insurance_coverage
    description: "Patient insurance coverage details including plans and carriers"
    meta:
      owner: "Insurance Team"
      refresh: "daily"
      business_system: "System B: Insurance Processing"
    columns:
      - name: patplan_id
        description: "Unique identifier for a patient-plan assignment"
        tests:
          - unique
          - not_null
      - name: patient_id
        description: "Patient covered by the insurance"
        tests:
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: inssub_id
        description: "Insurance subscriber identifier"
      - name: is_primary
        description: "Flag indicating if this is the primary insurance"
      - name: insurance_rank
        description: "Rank of this insurance (Primary, Secondary, Tertiary, Other)"
      - name: subscriber_id
        description: "Patient ID of the subscriber (may be the patient or another family member)"
      - name: carrier_id
        description: "Identifier for the insurance carrier"
      - name: carrier_name
        description: "Name of the insurance carrier"
      - name: plan_name
        description: "Name of the insurance plan"
      - name: plan_type
        description: "Type of insurance plan"
      - name: group_name
        description: "Name of the insurance group"
      - name: group_num
        description: "Group number for the insurance plan"
      - name: verification_status
        description: "Current verification status of the insurance"
      - name: last_verify_date
        description: "Date the insurance was last verified"
      - name: insurance_status
        description: "Overall status of the insurance (Active, Expired, Never Verified)"

  - name: int_claim_details
    description: "Insurance claim details with procedures and tracking status"
    meta:
      owner: "Insurance Team"
      refresh: "daily"
      business_system: "System B: Insurance Processing"
    columns:
      - name: claim_id
        description: "Unique identifier for a claim"
      - name: claimproc_id
        description: "Unique identifier for a procedure on a claim"
        tests:
          - unique
          - not_null
      - name: patient_id
        description: "Patient associated with the claim"
        tests:
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: procedure_id
        description: "Procedure included in the claim"
        tests:
          - relationships:
              to: ref('int_procedure_complete')
              field: procedure_id
      - name: date_sent
        description: "Date the claim was sent to the insurance carrier"
      - name: date_received
        description: "Date the claim response was received from the carrier"
      - name: claim_status
        description: "Status of the overall claim"
      - name: claim_status_desc
        description: "Human-readable description of the claim status"
      - name: insurance_estimate
        description: "Estimated insurance payment for the procedure"
      - name: insurance_payment
        description: "Actual insurance payment received for the procedure"
      - name: write_off
        description: "Amount written off due to contractual adjustments"
      - name: tracking_status
        description: "Current status from claim tracking"
      - name: days_to_process
        description: "Number of days between claim submission and response"

  - name: int_payment_allocated
    description: "Payment allocations with splits across procedures"
    meta:
      owner: "Billing Team"
      refresh: "daily"
      business_system: "System C: Payment Allocation & Reconciliation"
    columns:
      - name: paysplit_id
        description: "Unique identifier for a payment split"
        tests:
          - unique
          - not_null
      - name: payment_id
        description: "Identifier for the parent payment"
        tests:
          - not_null
      - name: patient_id
        description: "Patient associated with the payment"
        tests:
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: procedure_id
        description: "Procedure to which the payment is applied"
        tests:
          - relationships:
              to: ref('int_procedure_complete')
              field: procedure_id
      - name: split_amount
        description: "Amount of the payment allocated to this procedure"
        tests:
          - custom_test_nonzero_amount
      - name: is_payment
        description: "Flag indicating if this is a payment (TRUE) or adjustment (FALSE)"
      - name: split_type
        description: "Type of split (0=normal, 288=unearned, 439=TP prepayment)"
      - name: split_type_desc
        description: "Human-readable description of the split type"
      - name: payment_date
        description: "Date the payment was received"
      - name: payment_type
        description: "Type of payment (e.g., Check, Credit Card, Cash)"
      - name: effective_date
        description: "Effective date for the payment (considers date_override)"
      - name: include_in_ar
        description: "Flag indicating if this payment should be included in AR calculations"

  - name: int_account_aging
    description: "Account aging analysis with buckets for days outstanding"
    meta:
      owner: "Billing Team"
      refresh: "hourly"
      business_system: "System D: AR Analysis"
    columns:
      - name: patient_id
        description: "Patient identifier"
        tests:
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: family_id
        description: "Family identifier for grouping related patients"
      - name: patient_balance
        description: "Total outstanding balance for the patient"
      - name: patient_current_0_30
        description: "Patient balance in the 0-30 days bucket"
      - name: patient_aging_31_60
        description: "Patient balance in the 31-60 days bucket"
      - name: patient_aging_61_90
        description: "Patient balance in the 61-90 days bucket"
      - name: patient_aging_91_plus
        description: "Patient balance in the 91+ days bucket"
      - name: family_balance
        description: "Total outstanding balance for the family"
      - name: family_current_0_30
        description: "Family balance in the 0-30 days bucket"
      - name: family_aging_31_60
        description: "Family balance in the 31-60 days bucket"
      - name: family_aging_61_90
        description: "Family balance in the 61-90 days bucket"
      - name: family_aging_91_plus
        description: "Family balance in the 91+ days bucket"
      - name: collection_risk_level
        description: "Risk level for collections (High, Medium, Low, Current)"
      - name: flag_for_collections
        description: "Flag indicating if this account should be sent to collections"

  - name: int_patient_communication
    description: "Patient communication logs with categorization and status"
    meta:
      owner: "Patient Relations Team"
      refresh: "daily"
      business_system: "System F: Patient-Clinic Communications"
    columns:
      - name: commlog_id
        description: "Unique identifier for a communication log entry"
        tests:
          - unique
          - not_null
      - name: patient_id
        description: "Patient involved in the communication"
        tests:
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: comm_date
        description: "Date of the communication"
      - name: comm_time
        description: "Time of the communication"
      - name: comm_datetime
        description: "Combined date and time of the communication"
      - name: mode_type
        description: "Communication channel (Email, Phone, Text, etc.)"
      - name: mode_type_desc
        description: "Human-readable description of the communication channel"
      - name: comm_type
        description: "Type of communication (Appointment, Billing, Recall, etc.)"
      - name: comm_type_desc
        description: "Human-readable description of the communication type"
      - name: note
        description: "Notes about the communication"
      - name: delivery_status
        description: "Status of the communication delivery (Sent, Received, Failed, etc.)"

  - name: int_patient_financial
    description: "Complete financial picture for each patient across all systems"
    meta:
      owner: "Financial Team"
      refresh: "daily"
      business_system: "Cross-System: Finance"
    columns:
      - name: patient_id
        description: "Patient identifier"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: total_completed_procedures
        description: "Total value of all completed procedures"
      - name: total_treatment_planned
        description: "Total value of all treatment planned procedures"
      - name: total_patient_payments
        description: "Total payments made by the patient"
      - name: total_insurance_payments
        description: "Total payments made by insurance"
      - name: total_write_offs
        description: "Total contractual adjustments and write-offs"
      - name: current_balance
        description: "Current outstanding balance"
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

  - name: int_treatment_journey
    description: "End-to-end patient treatment journey across all systems"
    meta:
      owner: "Operations Team"
      refresh: "daily"
      business_system: "Cross-System: Patient Journey"
    columns:
      - name: procedure_id
        description: "Unique identifier for a procedure"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('int_procedure_complete')
              field: procedure_id
      - name: patient_id
        description: "Patient who underwent the procedure"
        tests:
          - not_null
          - relationships:
              to: ref('int_patient_profile')
              field: patient_id
      - name: appointment_date
        description: "Date of the initial appointment"
      - name: procedure_date
        description: "Date the procedure was performed"
      - name: claim_date_sent
        description: "Date the insurance claim was sent"
      - name: claim_date_received
        description: "Date the insurance claim was processed"
      - name: payment_date
        description: "Date the patient payment was received"
      - name: journey_status
        description: "Current status of the treatment journey (Complete, Awaiting Insurance, Awaiting Payment, Unbilled, In Progress)"
      - name: days_appointment_to_procedure
        description: "Days elapsed between appointment and procedure"
      - name: days_procedure_to_claim
        description: "Days elapsed between procedure and insurance claim submission"
      - name: days_claim_to_payment
        description: "Days elapsed between claim submission and insurance payment"
      - name: days_procedure_to_payment
        description: "Days elapsed between procedure and patient payment"
      - name: remaining_balance
        description: "Remaining balance for this procedure"