-- opendental_analytics_opendentalbackup_01_03_2025.task definition

CREATE TABLE `task` (
  `TaskNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `TaskListNum` bigint(20) NOT NULL,
  `DateTask` date NOT NULL DEFAULT '0001-01-01',
  `KeyNum` bigint(20) NOT NULL,
  `Descript` text DEFAULT NULL,
  `TaskStatus` tinyint(3) unsigned NOT NULL,
  `IsRepeating` tinyint(3) unsigned NOT NULL,
  `DateType` tinyint(3) unsigned NOT NULL,
  `FromNum` bigint(20) NOT NULL,
  `ObjectType` tinyint(3) unsigned NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `UserNum` bigint(20) NOT NULL,
  `DateTimeFinished` datetime NOT NULL,
  `PriorityDefNum` bigint(20) NOT NULL,
  `ReminderGroupId` varchar(20) NOT NULL,
  `ReminderType` smallint(6) NOT NULL,
  `ReminderFrequency` int(11) NOT NULL,
  `DateTimeOriginal` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `DescriptOverride` varchar(255) NOT NULL,
  `IsReadOnly` tinyint(1) NOT NULL DEFAULT 0,
  `TriageCategory` bigint(20) NOT NULL,
  PRIMARY KEY (`TaskNum`),
  KEY `indexTaskListNum` (`TaskListNum`),
  KEY `KeyNum` (`KeyNum`),
  KEY `PriorityDefNum` (`PriorityDefNum`),
  KEY `SecDateTEdit` (`SecDateTEdit`),
  KEY `DateTimeOriginal` (`DateTimeOriginal`),
  KEY `TaskStatus` (`TaskStatus`),
  KEY `UserNum` (`UserNum`),
  KEY `TriageCategory` (`TriageCategory`)
) ENGINE=MyISAM AUTO_INCREMENT=2699 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_uca1400_ai_ci;