-- opendental_analytics_opendentalbackup_01_03_2025.paysplit definition

CREATE TABLE `paysplit` (
  `SplitNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `SplitAmt` double NOT NULL DEFAULT 0,
  `PatNum` bigint(20) NOT NULL,
  `ProcDate` date NOT NULL DEFAULT '0001-01-01',
  `PayNum` bigint(20) NOT NULL,
  `IsDiscount` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `DiscountType` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `ProvNum` bigint(20) NOT NULL,
  `PayPlanNum` bigint(20) NOT NULL,
  `DatePay` date NOT NULL DEFAULT '0001-01-01',
  `ProcNum` bigint(20) NOT NULL,
  `DateEntry` date NOT NULL DEFAULT '0001-01-01',
  `UnearnedType` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `FSplitNum` bigint(20) NOT NULL,
  `AdjNum` bigint(20) NOT NULL,
  `PayPlanChargeNum` bigint(20) NOT NULL,
  `PayPlanDebitType` tinyint(4) NOT NULL,
  `SecurityHash` varchar(255) NOT NULL,
  PRIMARY KEY (`SplitNum`),
  KEY `indexPatNum` (`PatNum`),
  KEY `ProcNum` (`ProcNum`),
  KEY `PayNum` (`PayNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `DatePay` (`DatePay`),
  KEY `PayPlanNum` (`PayPlanNum`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`),
  KEY `PrepaymentNum` (`FSplitNum`),
  KEY `indexPNAmt` (`ProcNum`,`SplitAmt`),
  KEY `AdjNum` (`AdjNum`),
  KEY `PayPlanChargeNum` (`PayPlanChargeNum`),
  KEY `ProvNum` (`ProvNum`),
  KEY `SecDateTEditPN` (`SecDateTEdit`,`PatNum`),
  KEY `idx_paysplit_proc_amt` (`ProcNum`,`SplitAmt`,`PayNum`)
) ENGINE=MyISAM AUTO_INCREMENT=1465484 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_uca1400_ai_ci;