-- opendental_analytics_opendentalbackup_01_03_2025.proctp definition

CREATE TABLE `proctp` (
  `ProcTPNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `TreatPlanNum` bigint(20) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `ProcNumOrig` bigint(20) NOT NULL,
  `ItemOrder` smallint(5) unsigned NOT NULL,
  `Priority` bigint(20) NOT NULL,
  `ToothNumTP` varchar(255) DEFAULT '',
  `Surf` varchar(255) DEFAULT '',
  `ProcCode` varchar(15) DEFAULT NULL,
  `Descript` varchar(255) DEFAULT '',
  `FeeAmt` double NOT NULL,
  `PriInsAmt` double NOT NULL,
  `SecInsAmt` double NOT NULL,
  `PatAmt` double NOT NULL,
  `Discount` double NOT NULL,
  `Prognosis` varchar(255) NOT NULL,
  `Dx` varchar(255) NOT NULL,
  `ProcAbbr` varchar(50) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateEntry` date NOT NULL DEFAULT '0001-01-01',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `FeeAllowed` double NOT NULL,
  `TaxAmt` double NOT NULL,
  `ProvNum` bigint(20) NOT NULL,
  `DateTP` date NOT NULL DEFAULT '0001-01-01',
  `ClinicNum` bigint(20) NOT NULL,
  `CatPercUCR` double NOT NULL,
  PRIMARY KEY (`ProcTPNum`),
  KEY `indexPatNum` (`PatNum`),
  KEY `indexTreatPlanNum` (`TreatPlanNum`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`),
  KEY `ProvNum` (`ProvNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `ProcNumOrig` (`ProcNumOrig`)
) ENGINE=MyISAM AUTO_INCREMENT=1871 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_uca1400_ai_ci;