-- opendental_analytics_opendentalbackup_01_03_2025.rxpat definition

CREATE TABLE `rxpat` (
  `RxNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `RxDate` date NOT NULL DEFAULT '0001-01-01',
  `Drug` varchar(255) DEFAULT '',
  `Sig` varchar(255) DEFAULT '',
  `Disp` varchar(255) DEFAULT '',
  `Refills` varchar(30) DEFAULT '',
  `ProvNum` bigint(20) NOT NULL,
  `Notes` varchar(255) DEFAULT '',
  `PharmacyNum` bigint(20) NOT NULL,
  `IsControlled` tinyint(4) NOT NULL,
  `DateTStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `SendStatus` tinyint(4) NOT NULL,
  `RxCui` bigint(20) NOT NULL,
  `DosageCode` varchar(255) NOT NULL,
  `ErxGuid` varchar(40) NOT NULL,
  `IsErxOld` tinyint(4) NOT NULL,
  `ErxPharmacyInfo` varchar(255) NOT NULL,
  `IsProcRequired` tinyint(4) NOT NULL,
  `ProcNum` bigint(20) NOT NULL,
  `DaysOfSupply` double DEFAULT NULL,
  `PatientInstruction` text NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `UserNum` bigint(20) NOT NULL,
  `RxType` tinyint(4) NOT NULL,
  PRIMARY KEY (`RxNum`),
  KEY `RxCui` (`RxCui`),
  KEY `ProcNum` (`ProcNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `ProvNum` (`ProvNum`),
  KEY `UserNum` (`UserNum`),
  KEY `PatNumRxType` (`PatNum`,`RxType`)
) ENGINE=MyISAM AUTO_INCREMENT=4968 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_uca1400_ai_ci;